apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: my-flask-app-container
        image: 255945442255.dkr.ecr.ap-southeast-1.amazonaws.com/luqman-flask-app:latest #Change
        ports:
        - containerPort: 5000
